1
ism-ektb/java-shareit pull request #2
Opened 2023-12-17 15:08 UTC by ism-ektb

2023-12-18 16:30 UTC, kriwsha requested changes

2023-12-18 16:30 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/service/ItemValidator.java
> +        User user = userMapper.dtoToModel(userService.findUserById(userId.get()));
Не совсем корректная архитектура. Валидатор - это вспомогательный элемент, от которого легко избавиться. Пробрасывать сюда сервис, который имеет более высокую ценность - плохая идея. Я бы рекомендовал найти какой-то вариант, когда валидатор не имеет внутри логику сервиса.

2023-12-18 20:36 UTC, ism-ektb commented on src/main/java/ru/practicum/shareit/item/service/ItemValidator.java
> +        User user = userMapper.dtoToModel(userService.findUserById(userId.get()));
Удалил ценные сервисы из валидатора

2023-12-19 07:57 UTC, kriwsha approved these changes

2024-01-04 17:24 UTC, merged